$ErrorActionPreference = "Stop"

if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    throw "uv is required. Install it from https://docs.astral.sh/uv/"
}

function Invoke-NativeStep {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Name,
        [Parameter(Mandatory = $true)]
        [scriptblock] $Command
    )

    & $Command
    if ($LASTEXITCODE -ne 0) {
        throw "$Name failed with exit code $LASTEXITCODE"
    }
}

# Bake the build tag into the package before packaging, so the identifier the
# executable reports describes the executable itself rather than whatever
# environment it is later run in. Set PEAKLIVE_BUILD_TAG to label a rebuild for
# a specific operator test; otherwise a UTC timestamp distinguishes it from any
# earlier build. See docs/build-identity.md.
$buildTag = $env:PEAKLIVE_BUILD_TAG
if ([string]::IsNullOrWhiteSpace($buildTag)) {
    $buildTag = "b" + (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmm")
}

$buildModule = Join-Path $PWD "src/peaklive/_build.py"
@"
"""Generated by scripts/build-windows.ps1. Not tracked in version control."""

BUILD_TAG = "$buildTag"
"@ | Set-Content -Path $buildModule -Encoding utf8

Invoke-NativeStep "uv sync" { uv sync --all-extras }
Invoke-NativeStep "ruff" { uv run ruff check . }
Invoke-NativeStep "pytest" { uv run python -m pytest }
Invoke-NativeStep "pyinstaller" { uv run python -m PyInstaller --noconfirm --clean peaklive.spec }

$identifier = (uv run python -m peaklive.version).Trim()
$exePath = Join-Path $PWD "dist/PeakLive.exe"
$hash = (Get-FileHash -Path $exePath -Algorithm SHA256).Hash

# Evidence the operator can quote when reporting on a specific executable.
@"
identifier: $identifier
build_tag: $buildTag
executable: $exePath
sha256: $hash
built_utc: $((Get-Date).ToUniversalTime().ToString("o"))
"@ | Set-Content -Path (Join-Path $PWD "dist/PeakLive.build.txt") -Encoding utf8

Write-Host "PeakLive executable: $exePath"
Write-Host "PeakLive build identity: $identifier"
Write-Host "Build evidence: $PWD\dist\PeakLive.build.txt"
