param(
    # CI validates dependencies, linting, and tests in dedicated steps before
    # invoking this script. Skipping that duplicate work leaves this script
    # useful for local release builds while keeping hosted packaging focused.
    [switch] $SkipValidation
)

$ErrorActionPreference = "Stop"

if (-not (Get-Command uv -ErrorAction SilentlyContinue)) {
    throw "uv is required. Install it from https://docs.astral.sh/uv/"
}

function Invoke-NativeStep {
    param(
        [Parameter(Mandatory = $true)]
        [string] $Name,
        [Parameter(Mandatory = $true)]
        [scriptblock] $Command
    )

    & $Command
    if ($LASTEXITCODE -ne 0) {
        throw "$Name failed with exit code $LASTEXITCODE"
    }
}

function Invoke-PyInstaller {
    param(
        [Parameter(Mandatory = $true)]
        [int] $TimeoutSeconds,
        [Parameter(Mandatory = $true)]
        [string] $WorkPath
    )

    # PyInstaller's default logging hides its progress. Keep the CI log useful
    # when binary collection or archive creation is unexpectedly slow, and
    # bound the process so a stuck runner cannot consume its whole job slot.
    $arguments = @(
        "run", "python", "-m", "PyInstaller", "--noconfirm", "--clean",
        "--log-level", "INFO", "--workpath", $WorkPath, "peaklive.spec"
    )
    # `uv` replaces its shim process on Windows, so Start-Process cannot
    # reliably report its child exit code. Invoke it directly to preserve the
    # native `$LASTEXITCODE` contract.
    & uv @arguments
    if ($LASTEXITCODE -ne 0) {
        throw "pyinstaller failed with exit code $LASTEXITCODE"
    }
}

# Bake the build tag into the package before packaging, so the identifier the
# executable reports describes the executable itself rather than whatever
# environment it is later run in. Set PEAKLIVE_BUILD_TAG to label a rebuild for
# a specific operator test; otherwise a UTC timestamp distinguishes it from any
# earlier build. See docs/build-identity.md.
$buildTag = $env:PEAKLIVE_BUILD_TAG
if ([string]::IsNullOrWhiteSpace($buildTag)) {
    $buildTag = "b" + (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmm")
}

$buildModule = Join-Path $PWD "src/peaklive/_build.py"
@"
"""Generated by scripts/build-windows.ps1. Not tracked in version control."""

BUILD_TAG = "$buildTag"
"@ | Set-Content -Path $buildModule -Encoding utf8

if (-not $SkipValidation) {
    Invoke-NativeStep "uv sync" { uv sync --all-extras }
    Invoke-NativeStep "ruff" { uv run ruff check . }
    Invoke-NativeStep "pytest" { uv run python -m pytest }
}
# Keep PyInstaller's disposable work tree outside a synced checkout. Windows
# can retain a transient handle beneath the default `build/` directory after a
# prior run, which makes `--clean` fail before packaging begins.
Invoke-PyInstaller -TimeoutSeconds 900 -WorkPath (Join-Path $env:TEMP "peaklive-pyinstaller-$PID")

$identifier = (uv run python -m peaklive.version).Trim()
$exePath = Join-Path $PWD "dist/PeakLive.exe"
$hash = (Get-FileHash -Path $exePath -Algorithm SHA256).Hash

# Evidence the operator can quote when reporting on a specific executable.
@"
identifier: $identifier
build_tag: $buildTag
executable: $exePath
sha256: $hash
built_utc: $((Get-Date).ToUniversalTime().ToString("o"))
"@ | Set-Content -Path (Join-Path $PWD "dist/PeakLive.build.txt") -Encoding utf8

Write-Host "PeakLive executable: $exePath"
Write-Host "PeakLive build identity: $identifier"
Write-Host "Build evidence: $PWD\dist\PeakLive.build.txt"
